apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  labels:
    tier: frontend
    app: nginx
spec:
  selector:
    matchLabels:
      tire: frontend
  replicas: 3
  template:
    metadata:
      labels:
        tire: frontend
    spec:
      containers:
        - name: nginx
          image: nginx  
