apiVersion: v1
kind: Pod
metadata:
  name: myapp-busybox
  labels:
    name: frentend
spec:
  containers:
  - name: busybox
    image: busybox
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 8085
