apiVersion: v1
kind: ReplicationController
metadata:
  name: myapp-rc
spec:
  replicas: 3
  selector:
    app: myapp-rc
  template:
    metadata:
      name: myapp-nginx
      labels:
        app: myapp-nginx
    spec:
      containers:
        - name: ngnix
          image: ngnix
          ports:
            - containerPort: 8080

