apiVersion: v1
kind: Service
metadata:
  name:  myapp-service
spec:
  selector:
    app:  myapp-service
  type: NodePort
  ports:
  - name:  myapp-port
    port:  80
    targetPort:  8080
    nodePort: 30008